openapi: 3.0.3
info:
  title: Attendance & Leave API
  version: 1.0.0
paths:
  /api/attendance/mark/:
    post:
      operationId: attendance_mark_create
      tags:
      - attendance
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Attendance'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Attendance'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Attendance'
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Attendance'
          description: ''
  /api/attendance/my/:
    get:
      operationId: attendance_my_list
      tags:
      - attendance
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Attendance'
          description: ''
  /api/attendance/reports/daily/:
    get:
      operationId: attendance_reports_daily_retrieve
      tags:
      - attendance
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DailyReport'
          description: ''
  /api/attendance/reports/monthly/:
    get:
      operationId: attendance_reports_monthly_retrieve
      tags:
      - attendance
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MonthlyReport'
          description: ''
  /api/attendance/team/:
    get:
      operationId: attendance_team_list
      tags:
      - attendance
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Attendance'
          description: ''
  /api/auth/login/:
    post:
      operationId: auth_login_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
  /api/auth/refresh/:
    post:
      operationId: auth_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /api/auth/register/:
    post:
      operationId: auth_register_create
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Register'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Register'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Register'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Register'
          description: ''
  /api/leaves/{id}/approve/:
    put:
      operationId: leaves_approve_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - leaves
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LeaveRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/LeaveRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/LeaveRequest'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LeaveRequest'
          description: ''
    patch:
      operationId: leaves_approve_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - leaves
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedLeaveRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedLeaveRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedLeaveRequest'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LeaveRequest'
          description: ''
  /api/leaves/{id}/reject/:
    put:
      operationId: leaves_reject_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - leaves
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LeaveRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/LeaveRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/LeaveRequest'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LeaveRequest'
          description: ''
    patch:
      operationId: leaves_reject_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - leaves
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedLeaveRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedLeaveRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedLeaveRequest'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LeaveRequest'
          description: ''
  /api/leaves/apply/:
    post:
      operationId: leaves_apply_create
      tags:
      - leaves
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LeaveRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/LeaveRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/LeaveRequest'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LeaveRequest'
          description: ''
  /api/leaves/audit/logs/:
    get:
      operationId: leaves_audit_logs_list
      tags:
      - leaves
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AuditLog'
          description: ''
  /api/leaves/my/:
    get:
      operationId: leaves_my_list
      tags:
      - leaves
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LeaveRequest'
          description: ''
  /api/leaves/pending/:
    get:
      operationId: leaves_pending_list
      tags:
      - leaves
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LeaveRequest'
          description: ''
  /api/schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - ht
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
components:
  schemas:
    Attendance:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        status:
          $ref: '#/components/schemas/AttendanceStatusEnum'
        date:
          type: string
          format: date
          readOnly: true
        check_in:
          type: string
          format: time
          nullable: true
        check_out:
          type: string
          format: time
          nullable: true
        user:
          type: integer
          readOnly: true
      required:
      - date
      - id
      - user
    AttendanceStatusEnum:
      enum:
      - PRESENT
      - ABSENT
      - HALF_DAY
      type: string
      description: |-
        * `PRESENT` - Present
        * `ABSENT` - Absent
        * `HALF_DAY` - Half Day
    AuditLog:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        action:
          type: string
          readOnly: true
        target_id:
          type: integer
          readOnly: true
          nullable: true
        target_model:
          type: string
          readOnly: true
        from_state:
          type: string
          readOnly: true
          nullable: true
        to_state:
          type: string
          readOnly: true
          nullable: true
        timestamp:
          type: string
          format: date-time
          readOnly: true
        metadata:
          readOnly: true
        actor:
          type: integer
          readOnly: true
          nullable: true
      required:
      - action
      - actor
      - from_state
      - id
      - metadata
      - target_id
      - target_model
      - timestamp
      - to_state
    DailyReport:
      type: object
      properties:
        date:
          type: string
          format: date
        present:
          type: integer
        absent:
          type: integer
        half_day:
          type: integer
      required:
      - absent
      - date
      - half_day
      - present
    LeaveRequest:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        leave_type:
          $ref: '#/components/schemas/LeaveTypeEnum'
        start_date:
          type: string
          format: date
        end_date:
          type: string
          format: date
        reason:
          type: string
        status:
          allOf:
          - $ref: '#/components/schemas/LeaveRequestStatusEnum'
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        employee:
          type: integer
          readOnly: true
        manager:
          type: integer
          nullable: true
      required:
      - created_at
      - employee
      - end_date
      - id
      - leave_type
      - reason
      - start_date
      - status
      - updated_at
    LeaveRequestStatusEnum:
      enum:
      - PENDING
      - APPROVED
      - REJECTED
      type: string
      description: |-
        * `PENDING` - Pending
        * `APPROVED` - Approved
        * `REJECTED` - Rejected
    LeaveTypeEnum:
      enum:
      - SICK
      - CASUAL
      - EARNED
      type: string
      description: |-
        * `SICK` - Sick
        * `CASUAL` - Casual
        * `EARNED` - Earned
    MonthlyReport:
      type: object
      properties:
        month:
          type: integer
        user:
          type: integer
        present:
          type: integer
        absent:
          type: integer
        half_day:
          type: integer
      required:
      - absent
      - half_day
      - month
      - present
      - user
    PatchedLeaveRequest:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        leave_type:
          $ref: '#/components/schemas/LeaveTypeEnum'
        start_date:
          type: string
          format: date
        end_date:
          type: string
          format: date
        reason:
          type: string
        status:
          allOf:
          - $ref: '#/components/schemas/LeaveRequestStatusEnum'
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        employee:
          type: integer
          readOnly: true
        manager:
          type: integer
          nullable: true
    Register:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        password:
          type: string
          writeOnly: true
        password2:
          type: string
          writeOnly: true
        role:
          $ref: '#/components/schemas/RoleEnum'
      required:
      - id
      - password
      - password2
      - username
    RoleEnum:
      enum:
      - EMPLOYEE
      - MANAGER
      - HR_ADMIN
      type: string
      description: |-
        * `EMPLOYEE` - Employee
        * `MANAGER` - Manager
        * `HR_ADMIN` - HR Admin
    TokenObtainPair:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
      - access
      - password
      - refresh
      - username
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          writeOnly: true
      required:
      - access
      - refresh
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
