# Generated by Django 6.0.3 on 2026-04-06 20:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leaves", "0003_leaverequest_leaves_leav_employe_7236fb_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["actor", "timestamp"], name="leaves_audi_actor_i_571f97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["target_model", "target_id"],
                name="leaves_audi_target__4dbd7a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["timestamp"], name="leaves_audi_timesta_313f50_idx"
            ),
        ),
    ]
